### PR TITLE
Fixing duplicate land from land buy due to extra action args error

### LINKED ISSUE #385: Two children with the same key
`Warning: Encountered two children with the same key, `%s`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.%s, 0x0e30f72f435ee22b208f458f5bbd39435d33dea2e308edd9b8e96c4805a2b28c, `
```
    in RCTScrollContentView (at ScrollView.js:852)
    in RCTScrollView (at ScrollView.js:977)
    in ScrollView (at VirtualizedList.js:1062)
    in VirtualizedList (at FlatList.js:662)
    in FlatList (at LandForSaleList.js:22)
    in LandForSaleList (at ListLandForSaleScreen.js:135)
    in RCTView (at View.js:44)
    in Root (at connectStyle.js:384)
    in Styled(Root) (at ListLandForSaleScreen.js:134)
    in ListLandForSaleScreen (created by Context.Consumer)
    in Connect(ListLandForSaleScreen) (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:797)
    in RCTView (at View.js:44)
    in AnimatedComponent (at StackViewCard.js:69)
    in RCTView (at View.js:44)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.js:57)
    in Card (at createPointerEventsContainer.js:27)
    in Container (at StackViewLayout.js:862)
    in RCTView (at View.js:44)
    in ScreenContainer (at StackViewLayout.js:313)
    in RCTView (at View.js:44)
    in AnimatedComponent (at StackViewLayout.js:309)
    in Handler (at StackViewLayout.js:302)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:79)
    in RCTView (at View.js:44)
    in Transitioner (at StackView.js:22)
    in StackView (at createNavigator.js:61)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at SceneView.js:9)
    in SceneView (at DrawerView.js:149)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in ResourceSavingScene (at DrawerView.js:148)
    in RCTView (at View.js:44)
    in ScreenContainer (at DrawerView.js:138)
    in RCTView (at View.js:44)
    in AnimatedComponent (at DrawerLayout.js:440)
    in RCTView (at View.js:44)
    in AnimatedComponent (at DrawerLayout.js:439)
    in Handler (at DrawerLayout.js:495)
    in DrawerLayout (at DrawerView.js:165)
    in DrawerView (at createNavigator.js:61)
    in Navigator (at createAppContainer.js:387)
    in NavigationContainer (at App.js:114)
    in RCTView (at View.js:44)
    in Root (at connectStyle.js:384)
    in Styled(Root) (at App.js:113)
    in Provider (at App.js:112)
    in App (at withExpoRoot.js:22)
    in RootErrorBoundary (at withExpoRoot.js:21)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)
```

### PR DESCRIPTION
**Pull request by pcowgill**
### Issue link

https://github.com/tasitlabs/tasit/issues/385

### Auto-close the issue?

Closes #385

### Types of changes

Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: decentraland/screens/BuyLandScreen/BuyLandScreen.js [hunk 1]
```diff
@@ -119,16 +138,19 @@ export class BuyLandScreen extends React.Component {
...
       marketplaceContract.setAccount(account);
+
+      // TODO: Add extra param back in to reproduce the error
+      // state that we should handle better
       const action = marketplaceContract.safeExecuteOrder(
         nftAddress,
         `${assetId}`,
         `${priceInWei}`,
-        `${fingerprint}`,
-        gasParams
```
Comment (pcowgill) [inline decentraland/screens/BuyLandScreen/BuyLandScreen.js]: @marcelomorgado This was the issue that led us down an error path we hadn't traversed before

File: decentraland/redux/reducers.js [hunk 2]
```diff
@@ -87,17 +87,31 @@ const landToBuy = createReducer(null, {
...
+  // console.info("previous for sale list length", assetsForSale.length);
+  console.info("append landForSale id", id);
   return { ...state, list: [...state.list, landForSale] };
 };
 
 const removeLandForSale = (state, action) => {
   const { landForSale } = action;
+  const { id } = landForSale;
+  console.info("remove landForSale id", id);
   let { list: assetsForSale } = state;
```
Comment (pcowgill) [inline decentraland/redux/reducers.js]: @marcelomorgado Any reason not to convert this to a `const`?

Comment (marcelomorgado) [reply decentraland/redux/reducers.js]: No, no reason.

File: decentraland/screens/BuyLandScreen/BuyLandScreen.js (hunk 1 above)
Comment (pcowgill) [reply decentraland/screens/BuyLandScreen/BuyLandScreen.js]: Resolving this since you gave it a thumbs up

File: decentraland/redux/reducers.js (hunk 2 above)
Comment (pcowgill) [reply decentraland/redux/reducers.js]: Updated this in another feature branch. Closing this.
