### PR TITLE
Optimistic update

### LINKED ISSUE #214: Land parcel should be removed from assets for sale list in redux immediately after triggering the buy and added back if the buy fails to go through
(In other words, optimistic updates)

### PR DESCRIPTION
**Pull request by marcelomorgado**
### Issue link

#214 

### Auto-close the issue?

Closes #214 

### Types of changes

New feature (non-breaking change that adds functionality)

### CODE REVIEW

**Comment by pcowgill** [comment]
@marcelomorgado I'm going to start reviewing this now - one top of mind question before I start is whether the error path is handled. Noting that so I don't forget while reviewing it.

File: decentraland/redux/reducers.js [hunk 1]
```diff
@@ -66,6 +67,8 @@ function myAssets(state = { list: [] }, action) {
   switch (type) {
     case ADD_TO_MY_ASSETS_LIST:
       return { ...state, list: [myAsset, ...state.list] };
+    case REMOVE_MY_ASSET_FROM_LIST:
+      return { ...state, list: state.list.filter(val => val !== myAsset) };
```
Comment (pcowgill) [inline decentraland/redux/reducers.js]: I wonder if this would be more readable split out into a couple lines of code. Certainly a matter of personal preference and not important in a vacuum, but having the style match throughout the codebase has some value for understandability. Thoughts?

File: decentraland/screens/BuyLandScreen.js [hunk 2]
```diff
@@ -53,16 +60,29 @@ export class BuyLandScreen extends React.Component {
 
     const onSuccess = () => {
       showInfo(`${typeDescription} bought successfully.`);
-      removeLandForSale(landForSale);
-      addToMyAssetsList(asset);
+    };
+
+    const onError = () => {
```
Comment (pcowgill) [inline decentraland/screens/BuyLandScreen.js]: In a future version I wonder whether we want the error payload to contain all the data we'd need to use to react to the error event (here, the asset in question)

File: decentraland/screens/BuyLandScreen.js [hunk 3]
```diff
@@ -53,16 +60,29 @@ export class BuyLandScreen extends React.Component {
...
+      removeMyAssetFromList(asset);
+      addLandForSaleToList(landForSale);
```
Comment (pcowgill) [inline decentraland/screens/BuyLandScreen.js]: It's weird that the argument for these two functions isn't the exact same object or asset id. What's the difference between the contents of these two variables?

File: decentraland/screens/BuyLandScreen.js [hunk 4]
```diff
@@ -53,16 +60,29 @@ export class BuyLandScreen extends React.Component {
 
     const onSuccess = () => {
       showInfo(`${typeDescription} bought successfully.`);
-      removeLandForSale(landForSale);
-      addToMyAssetsList(asset);
+    };
+
+    const onError = () => {
+      removeMyAssetFromList(asset);
```
Comment (pcowgill) [inline decentraland/screens/BuyLandScreen.js]: We probably want to show an alert or toast in this case

File: decentraland/screens/BuyLandScreen.js [hunk 5]
```diff
@@ -53,16 +60,29 @@ export class BuyLandScreen extends React.Component {
...
+      addLandForSaleToList(landForSale);
     };
 
     showInfo(`Buying the ${typeDescription.toLowerCase()}...`);
-    _executeOrder(landForSale, account, onSuccess);
+
+    // Optimistic UI update
+    removeLandForSale(landForSale);
+    addToMyAssetsList(asset);
```
Comment (pcowgill) [inline decentraland/screens/BuyLandScreen.js]: Maybe in a future PR, but the reducer for this action should probably set a pending state that is then set to confirmed onSuccess

File: decentraland/redux/reducers.js (hunk 1 above)
Comment (marcelomorgado) [reply decentraland/redux/reducers.js]: Agree. I'll do that.

File: decentraland/screens/BuyLandScreen.js (hunk 3 above)
Comment (marcelomorgado) [reply decentraland/screens/BuyLandScreen.js]: The `landForSale` is the sell order and wraps the asset. For example:
```javascript
const assetForSale = {
  priceInWei,
  expiresAt,
  asset: {
    id, type, x, y
  }
}
```
The `MyAssetsScreen` has assets owned by the user instead of sell orders because it's no longer an open sell order.

File: decentraland/screens/BuyLandScreen.js (hunk 4 above)
Comment (marcelomorgado) [reply decentraland/screens/BuyLandScreen.js]: Yes.

File: decentraland/screens/BuyLandScreen.js (hunk 5 above)
Comment (marcelomorgado) [reply decentraland/screens/BuyLandScreen.js]: Extracted to: https://github.com/tasitlabs/tasit/issues/253

File: decentraland/screens/BuyLandScreen.js (hunk 2 above)
Comment (marcelomorgado) [reply decentraland/screens/BuyLandScreen.js]: Could you clarify your point better?

File: decentraland/screens/BuyLandScreen.js (hunk 3 above)
Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.js]: Ah ok right, that makes sense - it seems like there may be some clever way to DRY that up a bit, but I don't have a concrete suggestion so let's keep it as-is for now. Feel free to resolve this after reading.

File: decentraland/screens/BuyLandScreen.js (hunk 4 above)
Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.js]: Great, thanks

File: decentraland/screens/BuyLandScreen.js (hunk 5 above)
Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.js]: Okay, great - thanks. Resolving this.

File: decentraland/screens/BuyLandScreen.js (hunk 2 above)
Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.js]: Oh, like if this were

`onError = (asset OR landForSale) => {`

and then below we used that data that was passed into the error handler to call actions rather than variables from a more global scope.

File: decentraland/redux/reducers.js (hunk 1 above)
Comment (marcelomorgado) [reply decentraland/redux/reducers.js]: Done.

**Comment by marcelomorgado** [comment]
After my last change here, I've changed the `addLandForSaleToList` to add the `assetForSale` on the beginning of the list since on error case it was backing to the end of the list.
As a side effect, on the app startup, the list refreshing is reloading to the user on each new asset addition. I think it's a good change because on the app loading adding on end seems that the list is loading faster (because only the on top 3 assets are shown to the user). What do you think?

File: decentraland/screens/BuyLandScreen.js (hunk 4 above)
Comment (marcelomorgado) [reply decentraland/screens/BuyLandScreen.js]: Done.

File: decentraland/screens/BuyLandScreen.js (hunk 2 above)
Comment (marcelomorgado) [reply decentraland/screens/BuyLandScreen.js]: Done.

Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.js]: Cool, thanks! Resolving this.

File: decentraland/screens/BuyLandScreen.js (hunk 4 above)
Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.js]: Resolving this. Thanks.

**Comment by pcowgill** [comment]
> After my last change here, I've changed the `addLandForSaleToList` to add the `assetForSale` on the beginning of the list since on error case it was backing to the end of the list.
> As a side effect, on the app startup, the list refreshing is reloading to the user on each new asset addition. I think it's a good change because on the app loading adding on end seems that the list is loading faster (because only the on top 3 assets are shown to the user). What do you think?

Makes sense and sounds good to me!

File: decentraland/redux/reducers.js (hunk 1 above)
Comment (pcowgill) [reply decentraland/redux/reducers.js]: Thanks! Resolving

File: decentraland/redux/reducers.js [hunk 6]
```diff
@@ -67,8 +68,12 @@ function myAssets(state = { list: [] }, action) {
   switch (type) {
     case ADD_TO_MY_ASSETS_LIST:
       return { ...state, list: [myAsset, ...state.list] };
-    case REMOVE_MY_ASSET_FROM_LIST:
-      return { ...state, list: state.list.filter(val => val !== myAsset) };
+    case REMOVE_MY_ASSET_FROM_LIST: {
+      const { list: myAssets } = state;
+      const toRemove = myAsset;
+      const list = myAssets.filter(asset => asset !== toRemove);
```
Comment (pcowgill) [inline decentraland/redux/reducers.js]: It's probably overkill, but we could dry this logic up with the reducer for land for sale if we wanted to. Doesn't need to happen in this PR or ever, though. Just a thought.

**Comment by pcowgill** [comment]
@marcelomorgado Merging this now! Great work!

File: decentraland/redux/reducers.js (hunk 6 above)
Comment (marcelomorgado) [reply decentraland/redux/reducers.js]: Done on https://github.com/tasitlabs/tasit/pull/256. Resolving this.
