### PR TITLE
MyLand refresh/navigation fix

### LINKED ISSUE #267: After purchase navigation
After purchase, user is being moved to `ListLandForSaleScreen`, to improve the UI flow, that navigation should be change to redirect the user to `MyAssetsScreen`.
We've made a tryout on that and faced some issues that need to me addressed:

- After purchase, if the user clicks on the `Land For Sale` menu item, he will be moved to the `BuyLandScreen` showing the asset already bought, It's a bug. The menu link 'Land for Sale' should 
move the user to the `LandForSaleListScreen`.

- Since we are getting the list of users' land from blockchain during `MyAssetsScreen.componentDidMount` what is happening is:
On the first time of the app: User signs up, buy land and before the purchase process finished on the blockchain, he is moved to the `MyAssetsScreen` that will get no assets from blockchain and the list will be empty.
On the second use, the list will be loaded with the land bought on first use and so on...
The expected behavior only will happen if the user access the `MyAssetsScreen` before purcharse any asset.

### PR DESCRIPTION
**Pull request by marcelomorgado**
### Issue link

#267 

### Auto-close the issue?

Closes #267 

### Types of changes

Bug fix (non-breaking change that fixes an issue)

New feature (non-breaking change that adds functionality)

### Notes

Could you tell more about your last comment on the issue?

> I think the pattern to follow here is that there's a redux state update for each network request when request is initiated, when it succeeds, and when it fails due to timeout or error.

### CODE REVIEW

**Comment by pcowgill** [comment]
> > I think the pattern to follow here is that there's a redux state update for each network request when request is initiated, when it succeeds, and when it fails due to timeout or error.

> Could you tell more about your last comment on the issue?

Sure! Each type of network request - A) fetching my land; B) fetching land for sale; C) fetching account funding plus approval should have a name for that network request, and then when it it starts we save to redux that network request with name `BLA_BLA` is now in one of the enum list of options for network request status, between 1) loading, 2) succeeded, 3) failed.

The relevant one here would be the my land request.

Although going too far down this path might not be the best use of time because of the React Suspense discussion here https://github.com/tasitlabs/tasit/issues/197

Does that clarify it, or should I go into more detail?

**Comment by marcelomorgado** [comment]
> > > I think the pattern to follow here is that there's a redux state update for each network request when request is initiated, when it succeeds, and when it fails due to timeout or error.
> 
> > Could you tell more about your last comment on the issue?
> 
> Sure! Each type of network request - A) fetching my land; B) fetching land for sale; C) fetching account funding plus approval should have a name for that network request, and then when it it starts we save to redux that network request with name `BLA_BLA` is now in one of the enum list of options for network request status, between 1) loading, 2) succeeded, 3) failed.
> 
> The relevant one here would be the my land request.
> 
> Although going too far down this path might not be the best use of time because of the React Suspense discussion here #197
> 
> Does that clarify it, or should I go into more detail?

Oh, I see, something like this:

```javascript
{ type: 'FETCH_POSTS_REQUEST' }
{ type: 'FETCH_POSTS_FAILURE', error: 'Oops' }
{ type: 'FETCH_POSTS_SUCCESS', response: { ... } }
```

Extracted from redux doc.

**Comment by pcowgill** [comment]
> Oh, I see, something like this:
> 
> ```js
> { type: 'FETCH_POSTS_REQUEST' }
> { type: 'FETCH_POSTS_FAILURE', error: 'Oops' }
> { type: 'FETCH_POSTS_SUCCESS', response: { ... } }
> ```
> 
> Extracted from redux doc.

Yep, exactly

**Comment by pcowgill** [comment]
@marcelomorgado I know there were a couple issues being tracked in issue #267 . Have some of them since become obsolete? Just checking whether this PR indeed closes all of them.

File: decentraland/helpers/index.js [hunk 1]
```diff
@@ -171,6 +177,13 @@ export const listsAreEqual = (first, second) => {
   );
 };
 
+// Update any list having id as key field
```
Comment (pcowgill) [inline decentraland/helpers/index.js]:
```suggestion
// Update item from any list of objects having id as key field
```

**Comment by marcelomorgado** [comment]
> @marcelomorgado I know there were a couple issues being tracked in issue #267 . Have some of them since become obsolete? Just checking whether this PR indeed closes all of them.

This PR is addressing:
- Fix: Refreshing from blockchain was removed on-process purchase lands;
- Fix: After redirect user to `MyLandScreen` the menu link `Land For Sale` jumped the user to Buy Screen of already bought land.
- UX improvement: Redirect the user to `MyLandScreen` after clicking on `Buy` button (only possible after fixing both bugs above).

File: decentraland/redux/reducers.js [hunk 2]
```diff
@@ -83,13 +85,26 @@ function assetsForSale(state = { list: [], loadingInProgress: true }, action) {
...
+    myAssetAndStatus,
+    itemOrList,
+  } = action;
+
   switch (type) {
-    case ADD_TO_MY_ASSETS_LIST:
+    case PREPEND_TO_MY_ASSETS_LIST:
       return { ...state, list: [myAsset, ...state.list] };
-    case REMOVE_MY_ASSET_FROM_LIST: {
+    case APPEND_TO_MY_ASSETS_LIST: {
```
Comment (pcowgill) [inline decentraland/redux/reducers.js]: @marcelomorgado Out of curiosity, do you think this `myAssets` reducer function is getting a little large to reason about? I'm wondering whether we can split it out into a few functions that each handle fewer different type cases.

(Comment made on somewhat arbitrary line)

File: decentraland/screens/BuyLandScreen.js [hunk 3]
```diff
@@ -64,13 +69,15 @@ export class BuyLandScreen extends React.Component {
       // that catches the safeExecuteOrder successful event.
       await action.waitForNonceToUpdate();
 
+      updateMyAssetStatus(assetId, BOUGHT);
```
Comment (pcowgill) [inline decentraland/screens/BuyLandScreen.js]: I wonder about generalizing this term bought to something that could happen for any write tx. Like pending? And meta-tx might have state `BROADCAST` but not yet `PENDING`

File: decentraland/constants/MyAssetStatus.js [hunk 4]
```diff
@@ -0,0 +1,7 @@
+export const BUYING = "BUYING";
+export const BOUGHT = "BOUGHT";
+
+export default {
+  BUYING,
+  BOUGHT,
+};
```
Comment (pcowgill) [inline decentraland/constants/MyAssetStatus.js]: We'll definitely want a failed one here too

File: decentraland/screens/BuyLandScreen.js [hunk 5]
```diff
@@ -80,9 +87,11 @@ export class BuyLandScreen extends React.Component {
 
     // Optimistic UI update
     removeLandForSale(landForSale);
-    addToMyAssetsList(asset);
+    prependToMyAssetsList({ ...asset, status: BUYING });
 
-    navigation.navigate("ListLandForSaleScreen");
+    // Back to top of current Stack before navigate
+    navigation.dispatch(StackActions.popToTop());
```
Comment (pcowgill) [inline decentraland/screens/BuyLandScreen.js]: Interesting 👍

File: decentraland/screens/BuyLandScreen.test.js [hunk 6]
```diff
@@ -28,10 +29,11 @@ describe("BuyLandScreen", () => {
             myAssets={myAssets}
             selectedLandToBuy={estateForSale}
             removeLandForSale={removeLandForSale}
-            addToMyAssetsList={addToMyAssetsList}
-            removeMyAssetFromList={removeMyAssetFromList}
+            prependToMyAssetsList={prependToMyAssetsList}
+            removeFromMyAssetsList={removeFromMyAssetsList}
             prependLandForSaleToList={prependLandForSaleToList}
             setActionIdForMyAsset={setActionIdForMyAsset}
+            updateMyAssetStatus={updateMyAssetStatus}
```
Comment (pcowgill) [inline decentraland/screens/BuyLandScreen.test.js]: It's starting to feel odd the number of functions we're needing to pass through to this component

File: decentraland/screens/MyAssetsScreen.js [hunk 7]
```diff
@@ -1,25 +1,36 @@
...
+    const {
+      account,
+      myAssets: assetsFromState,
+      removeFromMyAssetsList,
+      appendToMyAssetsList,
+    } = this.props;
     if (account) {
       const { address } = account;
+
+      // Note: If an stored asset hasn't a status, assuming 'bought'.
```
Comment (pcowgill) [inline decentraland/screens/MyAssetsScreen.js]:
```suggestion
      // Note: If a stored asset doesn't have a status, assuming 'bought'.
```

File: decentraland/screens/MyAssetsScreen.js [hunk 8]
```diff
@@ -1,25 +1,36 @@
...
       const assetsFromBlockchain = await this._getAssetsFromBlockchain(address);
-      const shouldUpdate = !listsAreEqual(
-        assetsFromBlockchain,
-        assetsFromState
-      );
+      const shouldUpdate = !listsAreEqual(assetsFromBlockchain, boughtAssets);
       if (shouldUpdate) {
-        setMyAssetsList(assetsFromBlockchain);
+        removeFromMyAssetsList(boughtAssets);
+        appendToMyAssetsList(assetsFromBlockchain);
```
Comment (pcowgill) [inline decentraland/screens/MyAssetsScreen.js]: If an asset was locally there but ends up being removed as a result of this, I think we should log something at a minimum, and eventually add some UI indication that something unexpected happened

**Comment by pcowgill** [comment]
> > @marcelomorgado I know there were a couple issues being tracked in issue #267 . Have some of them since become obsolete? Just checking whether this PR indeed closes all of them.
> 
> This PR is addressing:
> 
>     * Fix: Refreshing from blockchain was removed on-process purchase lands;
> 
>     * Fix: After redirect user to `MyLandScreen` the menu link `Land For Sale` was jumped the user to Buy Screen of already bought land.
> 
>     * UX improvement: Redirect the user to `MyLandScreen` after clicking on `Buy` button (only possible after fixing both bugs above).

Awesome, this is a big improvement!!

File: decentraland/redux/reducers.js (hunk 2 above)
Comment (marcelomorgado) [reply decentraland/redux/reducers.js]: I agree. I've followed some tips from https://redux.js.org/recipes/structuring-reducers/refactoring-reducer-example seems better now? We can do the same for all reducers or even extract a file for each reducer.

File: decentraland/screens/BuyLandScreen.js (hunk 3 above)
Comment (marcelomorgado) [reply decentraland/screens/BuyLandScreen.js]: I'm using `BOUGHT` as a successful status. Maybe make more sense when we were using event listeners (i.e.: confs > 7)?

File: decentraland/redux/reducers.js (hunk 2 above)
Comment (pcowgill) [reply decentraland/redux/reducers.js]: Okay, sounds good, thanks! I'll take a look.

File: decentraland/constants/MyAssetStatus.js (hunk 4 above)
Comment (marcelomorgado) [reply decentraland/constants/MyAssetStatus.js]: I agree, but for now, we aren't tracking error events, should I add to the Constant anyway?

File: decentraland/redux/reducers.js [hunk 9]
```diff
@@ -85,51 +85,69 @@ function assetsForSale(state = { list: [], loadingInProgress: true }, action) {
...
+      return setActionIdForMyAsset(state, action);
+    case UPDATE_MY_ASSET_STATUS:
+      return updateMyAssetStatus(state, action);
     default:
       return state;
   }
 }
 
+const prependToMyAssetsList = (state, action) => {
+  const { myAsset } = action;
```
Comment (pcowgill) [inline decentraland/redux/reducers.js]: Is there a version of this where the action can just be the relevant piece of data for the reducer that will handle it? It seems redundant to also have to unpack a key/value that we already could have guessed based on the action name

Comment (pcowgill) [reply decentraland/redux/reducers.js]: Hmm, I think I take that back. Because the name of the action is also part of the action object

File: decentraland/redux/reducers.js (hunk 2 above)
Comment (pcowgill) [reply decentraland/redux/reducers.js]: Yep, I like the change to this reducer. Resolving this!

File: decentraland/constants/MyAssetStatus.js (hunk 4 above)
Comment (pcowgill) [reply decentraland/constants/MyAssetStatus.js]: Maybe just a TODO in that file rather than actually adding it.

Comment (pcowgill) [reply decentraland/constants/MyAssetStatus.js]: Even if it's not an error from the contract we can track, we might use it if the phone is offline and the request itself fails to be made

File: decentraland/screens/BuyLandScreen.js (hunk 3 above)
Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.js]: Yep. But I'm saying since we might want to use this pattern for the MANA funding, for instance, where `BOUGHT` wouldn't describe the success state well.

That said, keeping an action-specific name for success might be better - I'm not sure.

Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.js]: But yeah, we can wait until we're using event listeners more to formalize a standard around how to handle this stuff

File: decentraland/screens/BuyLandScreen.test.js (hunk 6 above)
Comment (marcelomorgado) [reply decentraland/screens/BuyLandScreen.test.js]: Yes, what is the best way to handle with this? Merge some actions?
Example:
```javascript
/// from
    removeLandForSale(landForSale);
    prependToMyAssetsList({ ...asset, status: BUYING });
// to
    moveAssetFromForSaleToMyAssets(landForSale, { ...asset, status: BUYING });
```

I'm not sure how the best way having an action changing more than one reducer (and if it's desirable). I'll take a look.

File: decentraland/redux/reducers.js (hunk 9 above)
Comment (marcelomorgado) [reply decentraland/redux/reducers.js]: I've found this on the [redux docs](https://redux.js.org/recipes/structuring-reducers/refactoring-reducer-example#combining-reducers-by-slice):
```javascript
function createReducer(initialState, handlers) {
  return function reducer(state = initialState, action) {
    if (handlers.hasOwnProperty(action.type)) {
      return handlers[action.type](state, action)
    } else {
      return state
    }
  }
}

const todosReducer = createReducer([], {
  ADD_TODO: addTodo,
  TOGGLE_TODO: toggleTodo,
  EDIT_TODO: editTodo
})
```

File: decentraland/screens/BuyLandScreen.test.js (hunk 6 above)
Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.test.js]: Hmm, let's see. I'm not sure why we would need:

`myAssets`

on the buy land screen.

Then I think this component can have one function called "process buy" for a piece of land.

Then that function up in whichever component / screen it's originally defined can handle splitting out into multiple actions for all the relevant state that's updated (removeLandForSale, prependToMyAssetsList, and setActionIdForMyAsset, and updateMyAssetStatus).

And for `removeFromMyAssetsList`, I'm not sure from first principles why that would be used when buying land anyway.

There's still only one reducer affected by any given action, but multiple actions are dispatched.

Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.test.js]: Hmm, only some of what I just said makes sense. I forgot this was the top level screen. I guess there are some functions that maybe should be defined outside of the scope of a given screen though, so they can react even if the user navigates away in the meantime?

File: decentraland/redux/reducers.js (hunk 9 above)
Comment (pcowgill) [reply decentraland/redux/reducers.js]: Ah yeah, exactly. Up to you whether that feels like a useful change to make or not.

File: decentraland/screens/BuyLandScreen.js (hunk 5 above)
Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.js]: Resolving this

File: decentraland/screens/BuyLandScreen.test.js (hunk 6 above)
Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.test.js]: So many of those functions are wrapped into the _buy function. I just didn't realize that the test would need them all defined in this way. Does it need to be passed in like this in the test for it to work?

Comment (marcelomorgado) [reply decentraland/screens/BuyLandScreen.test.js]: We can remove action functions from Proptype requirements, if we do so, it won't be needed.

File: decentraland/redux/reducers.js (hunk 9 above)
Comment (marcelomorgado) [reply decentraland/redux/reducers.js]: Done.

File: decentraland/constants/MyAssetStatus.js (hunk 4 above)
Comment (marcelomorgado) [reply decentraland/constants/MyAssetStatus.js]: I was thinking about that and these statuses were modeled to be used on the assets on the `MyLandScreen`.
If a purchase failed it'll be added to `LandForSaleScreen` again (it could have status but we aren't using it for now only on `MyLandScreen`). 
Maybe will be better having a status for the action instead of an action for the asset?

File: decentraland/screens/BuyLandScreen.test.js (hunk 6 above)
Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.test.js]: Hmm yeah, what value do we get out of `mapDispatchToProps`? It's possible we get some - I'm just not used to that approach.

File: decentraland/constants/MyAssetStatus.js (hunk 4 above)
Comment (pcowgill) [reply decentraland/constants/MyAssetStatus.js]: > Yeah, I think we want a data structure with all relevant actions not related to account funding that closely mirrors that data structure.

So both the my land screen and the list land for sale screen would use the state of that purchase actions data structure to reflect what is shown on its screen.

File: decentraland/redux/reducers.js (hunk 9 above)
Comment (pcowgill) [reply decentraland/redux/reducers.js]: Great, thanks. Resolving this.

File: decentraland/screens/BuyLandScreen.test.js (hunk 6 above)
Comment (marcelomorgado) [reply decentraland/screens/BuyLandScreen.test.js]: When we want to test some action behavior we still are able to pass it as props even if it wasn't on the `proptype` requirements. The only `pros` that I see is to have more strict component props definition. But I think worth more having less boilerplate.

File: decentraland/screens/MyAssetsScreen.js (hunk 8 above)
Comment (marcelomorgado) [reply decentraland/screens/MyAssetsScreen.js]: Since it's related to `Toast` make sense extract that?

Comment (pcowgill) [reply decentraland/screens/MyAssetsScreen.js]: Hmm, I think that may sound good but I'm not totally sure what you mean.

File: decentraland/screens/BuyLandScreen.test.js (hunk 6 above)
Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.test.js]: Yeah, if we were using them in the test it would make sense - and maybe that's a change we should make in the future and add an issue for. But for now the enzyme test isn't using them in any way https://github.com/tasitlabs/tasit/blob/766f5a4e8386e76ac4b7ec1e4a701e8bd67adfad/decentraland/screens/BuyLandScreen.test.js

Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.test.js]: I think we can have a strict component props definition for the top-level buy function but not the functions that function uses. If we ever want to test the subfuntctions with mocks, we can compile a mock version of the buy function from mocked subfunctions. Does that make sense?

File: decentraland/constants/MyAssetStatus.js (hunk 4 above)
Comment (marcelomorgado) [reply decentraland/constants/MyAssetStatus.js]: Ok.
We have `assetsForSale` and `myAssets` reducers.
An `assetForSale` stores the `asset` and other sell order info like `price` and `seller`.
On `myAssets` we store only the assets (Since a user could have an asset without buying from a marketplace).
I'm thinking about how will be the best way to store the `status` field. 
We are already storing the `actionId` (txhash) on the `asset` object, I'm thinking to move the status to here and change following your thoughts:
Before: `asset = { id, name, img, actionId, status }`
After: `asset = { id, name, img, action: { id, status } }`
Action status could be: `PENDING`, `FAILED`, `CONFIRMED` or `SUCCESSFULL`.
`CONFIRMED` or `SUCCESSFULL` could be splited soon to distinguish between 1-conf and 7-conf.
And that could be reused for all actions on the app. Make sense?

File: decentraland/screens/BuyLandScreen.test.js (hunk 6 above)
Comment (marcelomorgado) [reply decentraland/screens/BuyLandScreen.test.js]: I'm not sure since all functions from redux are passed as component prop separately.

File: decentraland/screens/MyAssetsScreen.js (hunk 8 above)
Comment (marcelomorgado) [reply decentraland/screens/MyAssetsScreen.js]: > add some UI indication that something unexpected happened

I thought to use `Toast` component for that, but it isn't working properly right now.

File: decentraland/redux/reducers.js [hunk 10]
```diff
@@ -21,90 +21,105 @@ import { removeFromList, updateListItem, toListIfNot } from "@helpers";
...
-      return { ...state, list };
-    }
-    case SET_LOADING_ASSETS_FOR_SALE_IN_PROGRESS:
-      return { ...state, loadingInProgress };
-    default:
-      return state;
-  }
-}
+const selectedLandToBuy = createReducer(null, {
+  [SELECT_LAND_TO_BUY]: selectLandToBuy,
```
Comment (pcowgill) [inline decentraland/redux/reducers.js]: The past tense for one name (selected) - the wrapped reducer - and present tense internal function (select) is a little confusing. Maybe let's pick one or the other?

File: decentraland/redux/reducers.js [hunk 11]
```diff
@@ -148,6 +163,21 @@ const updateMyAssetStatus = (state, action) => {
...
+    [APPEND_TO_MY_ASSETS_LIST]: appendToMyAssetsList,
+    [REMOVE_FROM_MY_ASSETS_LIST]: removeFromMyAssetsList,
+    [SET_MY_ASSETS_LIST]: setMyAssetsList,
+    [SET_ACTION_ID_FOR_MY_ASSET]: setActionIdForMyAsset,
+    [UPDATE_MY_ASSET_STATUS]: updateMyAssetStatus,
+  }
+);
+
+//
+// All all reducers
```
Comment (pcowgill) [inline decentraland/redux/reducers.js]: All all -> all

File: decentraland/redux/reducers.js (hunk 10 above)
Comment (marcelomorgado) [reply decentraland/redux/reducers.js]: `selectedLandToBuy` is the reducer/state that stores the selected land from user
`selectLandToBuy` is the action to select
Maybe change `selectedLandToBuy` to `landToBuy`?

File: decentraland/screens/BuyLandScreen.test.js (hunk 6 above)
Comment (marcelomorgado) [reply decentraland/screens/BuyLandScreen.test.js]: Oh wait, I've just realize that we are validating proptypes on `eslint` setup and if we'll just remove the action frunctions from we'll need to change the eslint config. I'll take a look if has a recommendation for the situation like ours.

File: decentraland/redux/reducers.js (hunk 11 above)
Comment (pcowgill) [reply decentraland/redux/reducers.js]: Thanks for addressing this. Resolving.

File: decentraland/redux/reducers.js (hunk 10 above)
Comment (pcowgill) [reply decentraland/redux/reducers.js]: Yeah, I like that suggestion. Thanks!

File: decentraland/screens/MyAssetsScreen.js (hunk 8 above)
Comment (pcowgill) [reply decentraland/screens/MyAssetsScreen.js]: Oh yeah. Plus I think we're maybe using Toasts a little bit too much? They work well as a placeholder for future UI elements, though. Maybe just log something for now and add a TODO comment in the code to reflect it in the UI?

File: decentraland/screens/BuyLandScreen.test.js (hunk 6 above)
Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.test.js]: > I'm not sure since all functions from redux are passed as component prop separately.

Do they need to be?

File: decentraland/constants/MyAssetStatus.js (hunk 4 above)
Comment (pcowgill) [reply decentraland/constants/MyAssetStatus.js]: SUCCESSFULL -> SUCCESSFUL

Comment (pcowgill) [reply decentraland/constants/MyAssetStatus.js]: > `CONFIRMED` or `SUCCESSFUL` could be splited soon to distinguish between 1-conf and 7-conf.

Love this idea!

Comment (pcowgill) [reply decentraland/constants/MyAssetStatus.js]: > After: `asset = { id, name, img, action: { id, status } }`

This looks good to me!

Comment (pcowgill) [reply decentraland/constants/MyAssetStatus.js]: > On `myAssets` we store only the assets (Since a user could have an asset without buying from a marketplace).

Makes sense. In this case the actionId would be for the transfer tx instead.

Comment (pcowgill) [reply decentraland/constants/MyAssetStatus.js]: Oh wait, there's one thing I'm suggesting that maybe isn't clear.

Let me know if this is too big of a refactor for now.

I think there should be a separate data structure in redux called `userActions`. It's just an object of all the actions the user has taken, keyed maybe by actionId?

(1) myAssets doesn't contain anything about the actions other than maybe actionId as a pointer. Either that OR
(2) `userActions` has a pointer to the assetId for each action and myAssts has nothing about actions.

I think I like option 2 better.

The myAssets screen uses both `userActions` and `myAssets` state from redux to figure out what to show.

The listLandForSale screen uses both `userActions` and `assetsForSale` to figure out what to show.

This is a little more complex at first glance, but this way we're not updating action status for a given assets in two spots, in both `myAssets` and `assetsForSale`

File: decentraland/screens/BuyLandScreen.test.js (hunk 6 above)
Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.test.js]: > Oh wait, I've just realize that we are validating proptypes on `eslint` setup and if we'll just remove the action functions from we'll need to change the eslint config. I'll take a look if has a recommendation for the situation like ours.

This is a naive question, but can we stop mapping dispatch to props?

Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.test.js]: Otherwise, maybe this is "code smell" that this really is just one "action", and our reducers + datastore have been designed in too complicated of a way and need to find a way to handle this single action.

File: decentraland/constants/MyAssetStatus.js (hunk 4 above)
Comment (marcelomorgado) [reply decentraland/constants/MyAssetStatus.js]: Nice!
I like option 2 too because we could have more than one action per asset (e.g.: many attempts before success) tracked too.

File: decentraland/screens/BuyLandScreen.test.js (hunk 6 above)
Comment (marcelomorgado) [reply decentraland/screens/BuyLandScreen.test.js]: Hmmmm maybe:
```javascript
const mapDispatchToProps = {
  removeLandForSale,
  prependLandForSaleToList,
  prependToMyAssetsList,
  removeFromMyAssetsList,
  setActionIdForMyAsset,
  updateMyAssetStatus,
};

// could be ?
const mapDispatchToProps = {
   buyFunctions: {
     removeLandForSale,
     prependLandForSaleToList,
     prependToMyAssetsList,
     removeFromMyAssetsList,
     setActionIdForMyAsset,
     updateMyAssetStatus, 
  }
};
```

File: decentraland/screens/MyAssetsScreen.js (hunk 8 above)
Comment (marcelomorgado) [reply decentraland/screens/MyAssetsScreen.js]: OK

File: decentraland/constants/MyAssetStatus.js (hunk 4 above)
Comment (pcowgill) [reply decentraland/constants/MyAssetStatus.js]: Yep, good point!

File: decentraland/screens/MyAssetsScreen.js (hunk 8 above)
Comment (marcelomorgado) [reply decentraland/screens/MyAssetsScreen.js]: Done. Should we log more detailed info (e.g.: which assetIds aren't on the blockchain)?

Comment (pcowgill) [reply decentraland/screens/MyAssetsScreen.js]: Sure!

File: decentraland/screens/BuyLandScreen.test.js (hunk 6 above)
Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.test.js]: What do you think about multiple reducers reacting to a single action instead?

Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.test.js]: There's an egghead lesson about it, so it must not be too much of an antipattern

https://egghead.io/lessons/react-respond-to-a-single-redux-action-in-multiple-reducers

Comment (marcelomorgado) [reply decentraland/screens/BuyLandScreen.test.js]: Hmmm, I'll take a look on that.

File: decentraland/redux/reducers.js (hunk 10 above)
Comment (marcelomorgado) [reply decentraland/redux/reducers.js]: Done.

Comment (pcowgill) [reply decentraland/redux/reducers.js]: Thanks. Resolving this.

File: decentraland/screens/MyAssetsScreen.js [hunk 12]
```diff
@@ -1,25 +1,40 @@
...
-      const shouldUpdate = !listsAreEqual(
-        assetsFromBlockchain,
-        assetsFromState
-      );
+      const shouldUpdate = !listsAreEqual(assetsFromBlockchain, boughtAssets);
       if (shouldUpdate) {
-        setMyAssetsList(assetsFromBlockchain);
+        // TODO: Add some UI indication that something unexpected happened
+        logWarn(
+          `Accounts' assets from blockchain aren't the same as the stored on the app.`
```
Comment (pcowgill) [inline decentraland/screens/MyAssetsScreen.js]:
```suggestion
          `Account's assets from blockchain aren't the same as the ones stored on the app.`
```

File: decentraland/constants/MyAssetStatus.js (hunk 4 above)
Comment (pcowgill) [reply decentraland/constants/MyAssetStatus.js]: This change should generalize well to other apps too, so that’s good

File: decentraland/screens/MyAssetsScreen.js (hunk 8 above)
Comment (marcelomorgado) [reply decentraland/screens/MyAssetsScreen.js]: Done.

File: decentraland/screens/BuyLandScreen.js (hunk 3 above)
Comment (marcelomorgado) [reply decentraland/screens/BuyLandScreen.js]: I think that this thread is related to the below one?

Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.js]: Yep, i think so. So we'll use `PENDING`, `FAILED`, `CONFIRMED` or `SUCCESSFUL` for this instead of `BOUGHT`, etc.?

File: decentraland/constants/MyAssetStatus.js (hunk 4 above)
Comment (pcowgill) [reply decentraland/constants/MyAssetStatus.js]: > Action status could be: `PENDING`, `FAILED`, `CONFIRMED` or `SUCCESSFUL`

And meta-tx or signed messages for contract-based accounts might have state `BROADCAST` but not yet `PENDING`

File: decentraland/screens/BuyLandScreen.js (hunk 3 above)
Comment (marcelomorgado) [reply decentraland/screens/BuyLandScreen.js]: Yes. I'm thinking to use `SUCCESSFUL` because it is a term less related to the blockchain. Make sense?

File: decentraland/screens/MyAssetsScreen.js (hunk 8 above)
Comment (pcowgill) [reply decentraland/screens/MyAssetsScreen.js]: Thanks! Resolving this

File: decentraland/screens/BuyLandScreen.js (hunk 3 above)
Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.js]: Yep, sounds good. We'll use SUCCESSFUL for the current bought state after nonce updates.

And then whenever we track a single confirmation vs. 7, successful will be for 7 confirmations and something like `PROBABLY_SUCCESSFUL` will be for 1 confirmation

File: decentraland/screens/MyAssetsScreen.js [hunk 13]
```diff
@@ -30,15 +30,33 @@ export class MyAssetsScreen extends React.Component {
...
+    const removedIds = fromStateIds.filter(
+      id => !fromBlockchainIds.includes(id)
+    );
+
+    logWarn(
+      `Account's assets from blockchain aren't the same as the ones stored on the app.`
+    );
+
+    if (addedIds.length > 0)
+      logWarn(`Some assets added to MyLandScreen. IDs: [${addedIds}]`);
```
Comment (pcowgill) [inline decentraland/screens/MyAssetsScreen.js]: This could probably be a `logInfo` rather than a `logWarn`. Either that or promote the removal one up from `logWarn` to `logError`

File: decentraland/constants/MyAssetStatus.js (hunk 4 above)
Comment (marcelomorgado) [reply decentraland/constants/MyAssetStatus.js]: Done.

Comment (pcowgill) [reply decentraland/constants/MyAssetStatus.js]: Awesome, thanks!! Resolving this

File: decentraland/screens/MyAssetsScreen.js (hunk 13 above)
Comment (marcelomorgado) [reply decentraland/screens/MyAssetsScreen.js]: Done.

File: decentraland/App.js [hunk 14]
```diff
@@ -11,6 +11,7 @@ import {
   setMyAssetsList,
   setAccountCreationStatus,
   setAccountCreationActions,
+  addUserAction,
```
Comment (pcowgill) [inline decentraland/App.js]: We can keep this as-is, but I first read it as "the action of adding a user"

Comment (pcowgill) [reply decentraland/App.js]: (And I know it's my fault for calling it `userAction` haha)

File: decentraland/App.js [hunk 15]
```diff
@@ -99,6 +102,21 @@ Is the config file correct?`;
 
   async _loadMyAssets() {
     const myAssets = await retrieveMyAssets();
+    const userActions = await retrieveUserActions();
+
+    // Handling with actions stored before
+    // the introduction of userAction state (<= 0.0.17)
```
Comment (pcowgill) [inline decentraland/App.js]: Good call adding this

File: decentraland/components/presentational/MyAssetsList.js [hunk 16]
```diff
@@ -11,27 +11,35 @@ import LargeText from "@presentational/LargeText";
 // https://medium.com/groww-engineering/stateless-component-vs-pure-component-d2af88a1200b
 export default class MyAssetsList extends React.PureComponent {
   render() {
-    const { myAssetsList, renderItem } = this.props;
-    const { length: listAmount } = myAssetsList;
+    const { myAssets, userActions, renderItem } = this.props;
+    const { length: listAmount } = myAssets;
```
Comment (pcowgill) [inline decentraland/components/presentational/MyAssetsList.js]: I forget, is length explicitly defined or is this a newer ECMAScript feature?

File: decentraland/constants/UserActionStatus.js [hunk 17]
```diff
@@ -0,0 +1,17 @@
+// To be used for meta-tx
+export const BROADCASTED = "BROADCASTED";
+
+export const PENDING = "PENDING";
+export const FAILED = "FAILED";
+
+// Note: We are using only 'SUCCESSFUL' for now
+// When we'll tracking confirmations that will be used for >= 7
```
Comment (pcowgill) [inline decentraland/constants/UserActionStatus.js]: we'll -> we're

File: decentraland/constants/UserActionStatus.js [hunk 18]
```diff
@@ -0,0 +1,17 @@
+// To be used for meta-tx
```
Comment (pcowgill) [inline decentraland/constants/UserActionStatus.js]: Also for contract-based accounts with signed messages that will be bundled into tx with enough signatures (which is a meta-tx in a sense but I'd argue not what people normally mean by meta-tx

File: decentraland/helpers/storage.js [hunk 19]
```diff
@@ -8,6 +8,19 @@ const MY_ASSETS_LIST = "MY_ASSETS_LIST";
...
+
+export const storeUserActions = async userActions => {
+  const strUserActions = _toString(userActions);
+  await _storeData(USER_ACTIONS, strUserActions, false);
+};
+
+export const retrieveUserActions = async () => {
+  const strUserActions = await _retrieveData(USER_ACTIONS);
+  const userActions = _fromString(strUserActions);
+  if (userActions === null) return [];
```
Comment (pcowgill) [inline decentraland/helpers/storage.js]: So we're storing `userActions` as an array rather than an object keyed by some id?

File: decentraland/screens/MyAssetsScreen.js [hunk 20]
```diff
@@ -1,42 +1,76 @@
...
+        addUserAction(actionsFromBlockchain);
       }
     }
   };
 
+  _getAssetsAndActionsFromBlockchain = async address => {
+    const assetsFromBlockchain = await this._getAssetsFromBlockchain(address);
+
+    const actionsFromBlockchain = assetsFromBlockchain.map(asset => {
+      const { actionId, id: assetId } = asset;
```
Comment (pcowgill) [inline decentraland/screens/MyAssetsScreen.js]: It's interesting that the `_getAssetsFromBlockchain` function has `actionId` available. I wouldn't have guessed that. I'll need to take another look at that function.

File: decentraland/screens/MyAssetsScreen.js [hunk 21]
```diff
@@ -1,42 +1,76 @@
...
+      const status = SUCCESSFUL;
+      return { actionId, assetId, status };
+    });
+
+    assetsFromBlockchain.forEach(asset => delete asset.actionId);
```
Comment (pcowgill) [inline decentraland/screens/MyAssetsScreen.js]: Is this temporary, or will we always need to do this?

File: decentraland/helpers/storage.js (hunk 19 above)
Comment (pcowgill) [reply decentraland/helpers/storage.js]: As long as userActions and the assets list looping through both won't be a problem. If it ever becomes one, we can change one from an array to an object with a key as an "index"

Comment (pcowgill) [reply decentraland/helpers/storage.js]: Are the "account info" actions an array or an object?

File: decentraland/screens/MyAssetsScreen.js [hunk 22]
```diff
@@ -80,15 +80,15 @@ export class MyAssetsScreen extends React.Component {
...
       `Account's assets from blockchain aren't the same as the ones stored on the app.`
     );
 
     if (addedIds.length > 0)
-      logWarn(`Some assets added to MyLandScreen. IDs: [${addedIds}]`);
+      logInfo(`Some assets added to MyLandScreen. IDs: [${addedIds}]`);
 
     if (removedIds.length > 0)
-      logWarn(`Some assets removed from MyLandScreen. IDs: [${removedIds}]`);
+      logInfo(`Some assets removed from MyLandScreen. IDs: [${removedIds}]`);
```
Comment (pcowgill) [inline decentraland/screens/MyAssetsScreen.js]: Wouldn't we still want this one to be a warn, though?

File: decentraland/screens/MyAssetsScreen.js (hunk 13 above)
Comment (pcowgill) [reply decentraland/screens/MyAssetsScreen.js]: Awesome, thanks. One remaining thing on this thread over here:

https://github.com/tasitlabs/tasit/pull/333/commits/edb45201c90a443512e3e92005ba9b63bad15494#r277888035

File: decentraland/screens/MyAssetsScreen.js (hunk 21 above)
Comment (pcowgill) [reply decentraland/screens/MyAssetsScreen.js]: (Not gating merging this PR)

File: decentraland/screens/MyAssetsScreen.js (hunk 20 above)
Comment (pcowgill) [reply decentraland/screens/MyAssetsScreen.js]: (Not gating merging this PR)

File: decentraland/helpers/storage.js (hunk 19 above)
Comment (pcowgill) [reply decentraland/helpers/storage.js]: (Not gating merging this PR)

File: decentraland/constants/UserActionStatus.js (hunk 18 above)
Comment (pcowgill) [reply decentraland/constants/UserActionStatus.js]:
```suggestion
// To be used for meta-tx
// Also for contract-based accounts with signed messages
// that will be bundled into tx with enough signatures 
```

File: decentraland/constants/UserActionStatus.js (hunk 17 above)
Comment (pcowgill) [reply decentraland/constants/UserActionStatus.js]:
```suggestion
// When we're tracking confirmations that will be used for >= 7
```

File: decentraland/components/presentational/MyAssetsList.js (hunk 16 above)
Comment (pcowgill) [reply decentraland/components/presentational/MyAssetsList.js]: (Not gating merging this PR)

File: decentraland/App.js (hunk 15 above)
Comment (pcowgill) [reply decentraland/App.js]: (Not gating merging this PR)

File: decentraland/App.js (hunk 14 above)
Comment (pcowgill) [reply decentraland/App.js]: (Not gating merging this PR)

File: decentraland/screens/BuyLandScreen.js (hunk 3 above)
Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.js]: Resolving this

File: decentraland/screens/BuyLandScreen.test.js (hunk 6 above)
Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.test.js]: I'm thinking we can make a new issue for this and merge this PR without making this change.

File: decentraland/screens/MyAssetsScreen.js (hunk 22 above)
Comment (pcowgill) [reply decentraland/screens/MyAssetsScreen.js]: At first I thought this might as well come in this PR, but given that it's the end of the day, I'll merge the PR as-is and we can circle back to this.

File: decentraland/components/presentational/MyAssetsList.js (hunk 16 above)
Comment (marcelomorgado) [reply decentraland/components/presentational/MyAssetsList.js]: Every array has the length property

File: decentraland/helpers/storage.js (hunk 19 above)
Comment (marcelomorgado) [reply decentraland/helpers/storage.js]: It is an array. But I think it should be an object.

File: decentraland/screens/MyAssetsScreen.js (hunk 20 above)
Comment (marcelomorgado) [reply decentraland/screens/MyAssetsScreen.js]: It comes from `DecentralandUtils`, each `sell order` has its `transactionHash` prop that is being renamed to `actionId` inside of `_getAssetsFromBlockchain` function.

File: decentraland/screens/MyAssetsScreen.js (hunk 21 above)
Comment (marcelomorgado) [reply decentraland/screens/MyAssetsScreen.js]: Since `sellOrders` from `DecentralandUtils` have `transactionHash`/`actionId` and we want to keep this info only on `userActions` state, I think it could be needed.

File: decentraland/screens/MyAssetsScreen.js (hunk 22 above)
Comment (marcelomorgado) [reply decentraland/screens/MyAssetsScreen.js]: > Wouldn't we still want this one to be a warn, though?

Yes, make sense.

File: decentraland/screens/BuyLandScreen.test.js (hunk 6 above)
Comment (marcelomorgado) [reply decentraland/screens/BuyLandScreen.test.js]: Extracted to: https://github.com/tasitlabs/tasit/issues/341

File: decentraland/screens/MyAssetsScreen.js (hunk 13 above)
Comment (marcelomorgado) [reply decentraland/screens/MyAssetsScreen.js]: Okay, I'll resolve this one since the other thread is tracking it.

File: decentraland/screens/MyAssetsScreen.js (hunk 22 above)
Comment (marcelomorgado) [reply decentraland/screens/MyAssetsScreen.js]: Extracted to: https://github.com/tasitlabs/tasit/issues/342

File: decentraland/helpers/storage.js (hunk 19 above)
Comment (marcelomorgado) [reply decentraland/helpers/storage.js]: Extracted to: https://github.com/tasitlabs/tasit/issues/342

File: decentraland/App.js (hunk 14 above)
Comment (marcelomorgado) [reply decentraland/App.js]: Extracted to: https://github.com/tasitlabs/tasit/issues/342

File: decentraland/components/presentational/MyAssetsList.js (hunk 16 above)
Comment (pcowgill) [reply decentraland/components/presentational/MyAssetsList.js]: Ahh yeah of course, this is basically the same as doing `myAssets.length`, and I remember that that's possible haha

Comment (pcowgill) [reply decentraland/components/presentational/MyAssetsList.js]: Resolving this

File: decentraland/helpers/storage.js (hunk 19 above)
Comment (pcowgill) [reply decentraland/helpers/storage.js]: Cool, thanks. Resolving this.

File: decentraland/screens/MyAssetsScreen.js (hunk 20 above)
Comment (pcowgill) [reply decentraland/screens/MyAssetsScreen.js]: Ah right, I think that makes sense - one question first thought:

When you say `sell order` here do you mean the listing of the item for sale in the marketplace or the execution of the order by the buyer?

File: decentraland/screens/MyAssetsScreen.js (hunk 21 above)
Comment (pcowgill) [reply decentraland/screens/MyAssetsScreen.js]: Thanks for the explanation. Is that the most compact/convenient way for the utils to return this information given how we'll use it going forward?

File: decentraland/screens/MyAssetsScreen.js (hunk 22 above)
Comment (pcowgill) [reply decentraland/screens/MyAssetsScreen.js]: Thanks! Resolving this

File: decentraland/screens/BuyLandScreen.test.js (hunk 6 above)
Comment (pcowgill) [reply decentraland/screens/BuyLandScreen.test.js]: Thanks. Resolving this.

File: decentraland/screens/MyAssetsScreen.js (hunk 13 above)
Comment (pcowgill) [reply decentraland/screens/MyAssetsScreen.js]: Good call. Thanks.

File: decentraland/App.js (hunk 14 above)
Comment (pcowgill) [reply decentraland/App.js]: Thanks! Resolving this.

File: decentraland/App.js (hunk 15 above)
Comment (pcowgill) [reply decentraland/App.js]: Resolving this

File: decentraland/screens/MyAssetsScreen.js (hunk 20 above)
Comment (marcelomorgado) [reply decentraland/screens/MyAssetsScreen.js]: the listing of the item for sale in the marketplace (sellOrder == assetForSale)

File: decentraland/screens/MyAssetsScreen.js (hunk 21 above)
Comment (marcelomorgado) [reply decentraland/screens/MyAssetsScreen.js]: I think so,
The source of that info is `CreatedOrder` events from Marketplace contract. So, each event has the assetId, type (nftAddress) and actionId (txhash).

Comment (pcowgill) [reply decentraland/screens/MyAssetsScreen.js]: Ah right, so there's not a separate lookup. Okay, makes sense! Thanks for the explanation. Resolving this.

File: decentraland/screens/MyAssetsScreen.js (hunk 20 above)
Comment (pcowgill) [reply decentraland/screens/MyAssetsScreen.js]: But we're in the `My assets` screen for this comment thread. So the tx hash of the listing of the item for sale in the marketplace has nothing to do with the tx hash we'll want to use to build the Etherscan link on this screen. Does that mean there may be a bug for this feature?

File: decentraland/constants/UserActionStatus.js (hunk 18 above)
Comment (pcowgill) [reply decentraland/constants/UserActionStatus.js]: Want to add this in in your current PR?

Comment (marcelomorgado) [reply decentraland/constants/UserActionStatus.js]: Done.

File: decentraland/screens/MyAssetsScreen.js (hunk 20 above)
Comment (marcelomorgado) [reply decentraland/screens/MyAssetsScreen.js]: Oh, good question. I've misunderstood the terms here. I've used `sellOrders` wrongly.
Actually, assets from an address are being got using events too. We are using `Transfer` events to get that, so, the txhash applies here too.

Comment (pcowgill) [reply decentraland/screens/MyAssetsScreen.js]: Got it - that makes sense. Thanks! Resolving this.

File: decentraland/constants/UserActionStatus.js (hunk 18 above)
Comment (pcowgill) [reply decentraland/constants/UserActionStatus.js]: Thanks! Resolving this
